// Code generated by 'yaegi extract yaegi-issues/common'. DO NOT EDIT.

//go:build go1.17
// +build go1.17

package symbols

import (
	"reflect"
	"yaegi-issues/common"
)

func init() {
	Symbols["yaegi-issues/common/common"] = map[string]reflect.Value{
		// type definitions
		"Cheater": reflect.ValueOf((*common.Cheater)(nil)),

		// interface wrapper definitions
		"_Cheater": reflect.ValueOf((*_yaegi_issues_common_Cheater)(nil)),
	}
}

// _yaegi_issues_common_Cheater is an interface wrapper for Cheater type
type _yaegi_issues_common_Cheater struct {
	IValue interface{}
	WCheat func()
}

func (W _yaegi_issues_common_Cheater) Cheat() {
	W.WCheat()
}
